### ISSUE TITLE
Readme tutorial erroring out at mint step

### ISSUE THREAD

**Issue by jameslin101** [metaplex-foundation/python-api#16]
I'm getting this error at this line
>>> metaplex_api.mint(api_endpoint, "7bxe7t1aGdum8o97bkuFeeBTcbARaBn9Gbv5sBd9DZPG", "VtdBygLSt1EJF5M3nUk5CRxuNNTyZFUsKJ4yUVcC6hh", "https://arweave.net/1eH7bZS-6HZH4YOc8T_tGp2Rq25dlhclXJkoa6U55mM/")
File "/Users/metaplex-foundation/python-api/metaplex/metadata.py", line 182, in get_metadata
    data = base64.b64decode(client.get_account_info(metadata_account)['result']['value']['data'][0])
TypeError: 'NoneType' object is not subscriptable

and stepping through the error it's crashing because there value is None 
-> data = base64.b64decode(client.get_account_info(metadata_account)['result']['value']['data'][0])
(Pdb) client.get_account_info(metadata_account)
{'jsonrpc': '2.0', 'result': {'context': {'slot': 83349421}, 'value': None}, 'id': 2}

**Comment by alikuddah** [comment]
are you on devnet? 

and are you using the same instructions as in the read me? 

try using different public keys and accounts.

**Comment by jameslin101** [comment]
Yup on dev net. Tried 2 different set of public keys and accounts

**Comment by jameslin101** [comment]
Ok that's strange tried a 3rd set today and it worked. Thanks.
