### ISSUE TITLE
Additional Decoration PDA of type MasterEdition

### ISSUE THREAD

**Issue by Sonal778** [metaplex-foundation/python-api#3]
Include an example in documentation, how we can pass decoration of MasterEdition & other sister PDA structs in Python as mentioned in [Metaplex Developer Guide](https://www.notion.so/Metaplex-Developer-Guide-afefbc19841744c28587ab948a08cfac).

> It would be really very helpful if it's implemented asap, so python developers can continue further.

**Comment by jarry-xiao** [comment]
Submitted a pull request with this feature. You can try it out by checking out the `bug-fixes-and-create-master-edition` branch

**Comment by jarry-xiao** [comment]
Should be resolved now
